version: '3'

services:
  wp:
    container_name: wp_core
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    hostname: wp-core
    ports:
      - 8080:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app/wp-config.php:/var/www/html/wp-config.php # Configs wordpress
      - ./wp-plugin:/var/www/html/wp-content/plugins # Plugins wordpress
      - ./wp-theme:/var/www/html/wp-content/themes # Themes wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db:db
    restart: always

  wpcli:
    container_name: wp_cli
    image: wordpress:cli
    hostname: wp-cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app/wp-config.php:/var/www/html/wp-config.php # Configs wordpress
      - ./wp-plugin:/var/www/html/wp-content/plugins # Plugins wordpress
      - ./wp-theme:/var/www/html/wp-content/themes # Themes wordpress
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_USER: "${DB_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 8081:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    #ports:
    #  - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_ROOT_USER}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: always

volumes:
  db_data:
